---

version: '3.2'
services:

  # Ingestion scripts
  ingestion-scripts:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: dpt-services-dashboard-scripts-ingestion-scripts
    image: teamdigitale/dpt-services-dashboard-scripts:latest
    env_file:
      - .env
    stdin_open: true
    tty: true
    depends_on:
      - mongodb
    volumes:
      - .:/opt/ingestion_scripts

  # Metabase
  metabase:
    container_name: dpt-services-dashboard-scripts-metabase
    image: metabase/metabase:v0.34.0
    stdin_open: true
    tty: true
    ports:
      - 3000:3000/tcp
    env_file:
      - .env
    volumes:
      - metabase-data:/metabase-data
    depends_on:
      - postgres
      - mongodb

  # MongoDB
  mongodb:
    image: bitnami/mongodb:4.2.2-debian-10-r0
    container_name: dpt-services-dashboard-scripts-mongo
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb

  # Postgres
  postgres:
    image: bitnami/postgresql:11.6.0-debian-10-r0
    container_name: dpt-services-dashboard-scripts-postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/pg_data
    env_file:
      - .env

volumes:
  pg_data:
  db-data:
  mongo-config:
  metabase-data:
  mongoclient:
